---
- targets:
    - 192.168.1.1
  labels:
    jobs: "solaris_exporter,blackbox-ssh"
    owner: "admin"
    os: "solaris"
    hostname: "server1"
    noAlarmOn: ""
- targets:
    - 192.168.1.2
  labels:
    jobs: "solaris_exporter,blackbox-ssh"
    owner: "admin"
    os: "solaris"
    hostname: "server2"
    noAlarmOn: ""

